server:
  port: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://integraciondb.cdjwmczabjfe.us-east-2.rds.amazonaws.com:3306/db_inventario
     username: integracion_adm
     password: Integracionsistemas2019 
